package com.qianyi.domain;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.log_type
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.crt_time
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.crt_user_id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private Long crtUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.crt_user_name
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private String crtUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.cont
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private String cont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.source_name
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.source_id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private Long sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.operation_type
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    private String operationType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.id
     *
     * @return the value of t_log.id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.id
     *
     * @param id the value for t_log.id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.log_type
     *
     * @return the value of t_log.log_type
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.log_type
     *
     * @param logType the value for t_log.log_type
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.crt_time
     *
     * @return the value of t_log.crt_time
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.crt_time
     *
     * @param crtTime the value for t_log.crt_time
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.crt_user_id
     *
     * @return the value of t_log.crt_user_id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public Long getCrtUserId() {
        return crtUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.crt_user_id
     *
     * @param crtUserId the value for t_log.crt_user_id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setCrtUserId(Long crtUserId) {
        this.crtUserId = crtUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.crt_user_name
     *
     * @return the value of t_log.crt_user_name
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public String getCrtUserName() {
        return crtUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.crt_user_name
     *
     * @param crtUserName the value for t_log.crt_user_name
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setCrtUserName(String crtUserName) {
        this.crtUserName = crtUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.cont
     *
     * @return the value of t_log.cont
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.cont
     *
     * @param cont the value for t_log.cont
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setCont(String cont) {
        this.cont = cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.source_name
     *
     * @return the value of t_log.source_name
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.source_name
     *
     * @param sourceName the value for t_log.source_name
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.source_id
     *
     * @return the value of t_log.source_id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.source_id
     *
     * @param sourceId the value for t_log.source_id
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.operation_type
     *
     * @return the value of t_log.operation_type
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.operation_type
     *
     * @param operationType the value for t_log.operation_type
     *
     * @mbggenerated Fri Sep 11 15:11:13 CST 2015
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }
}