server:
    port: 10000

system:
    appId: securityapp
    token: bWlubGlhCg==
    
spring:
    profile: dev
    application:
        name: miniapp

    datasource:
        testOnBorrow: true
        validationQuery: "SELECT 1"
#        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_mdl?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        name:
        username: root
        password:

security.jwt:
#  tokenExpirationTime: 15 # Number of minutes
    tokenExpirationTime: 10080 # Number of minutes
    refreshTokenExpTime: 10080 # Minutes
    tokenIssuer: http://minlia.com
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
  
swagger:
    title: 安全接口
    description: 安全接口
    version: 2.0
    contact: cloud@minlia.com
    path: /api/.*
    redirect: true

aliyun:
    sms:
        accessId: xxxx
        accessKey: xxxx
        endpoint: cn-hangzhou
        regionId: cn-hangzhou
        product: Sms
        domain: sms.aliyuncs.com
        signName: 测试

sms:
    templates:
        userRegistration: SMS_56155265
        resetPassword: SMS_56155265
        changePassword: SMS_56155265
        bindOrRegistration: SMS_56155265