server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true

system:
  appId: hsjs-product
  token: bWlubGlhCg==
  security:
    jwt:
      tokenExpirationTime: 90000 # Number of Seconds
      refreshTokenExpTime: 90000 # Seconds
      tokenIssuer: http://minlia.com
      tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus
  sms:
    type: aliyun

# SPRING PROFILES
spring:
  profile: prod
  aop:
    auto: true
  application:
    name: hsjs
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  http:
    encoding.enable: true
  session:
    store-type: none
  main:
    sources:
  mail:
    host: smtpdm.aliyun.com
    #    port: 465
    username: inquiry@dm.camelsc.com
    password: vNp8E7AKbRGYecW7
    default-encoding: UTF-8
    #    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true
      ssl:
        trust: smtpdm.aliyun.com
        enable: true
      socketFactory:
        port: 465
        #        class: javax.net.ssl.SSLSocketFactory
        class: com.sun.mail.util.MailSSLSocketFactory
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 300
        max-wait: 10000
        max-idle: 100
        min-idle: 50
    timeout: 0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hsjs?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password:
    hikari:
      pool-name: HsjsHikariCP           #连接池的名字。一般会出现在日志和JMX控制台中。默认值：auto-genenrated。建议取一个合适的名字，便于监控。
      minimum-idle: 5                   #池中最小空闲连接数量。默认值10
      maximum-pool-size: 15             #池中最大连接数（包括空闲和正在使用的连接）。默认值是10
      auto-commit: true                 #是否自动提交池中返回的连接。默认值为true。一般是有必要自动提交上一个连接中的事物的。如果为false，那么就需要应用层手动提交事物。
      idle-timeout: 600000              #空闲时间。仅在minimum-idle小于maximum-poop-size的时候才会起作用。默认值10分钟。根据应用实际情况做调整，对于一些间歇性流量达到峰值的应用，一般需要考虑设置的比间歇时间更大，防止创建数据库连接拖慢了应用速度。
      max-lifetime: 28740000            #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数
      connection-timeout: 30000         #连接超时时间。默认值为30s，可以接收的最小超时时间为250ms
      connection-test-query: SELECT 1
      leak-detection-threshold: 5000
#
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/**/*Mapper.xml,classpath*:mybatis/**/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id      #主键策略
      #table-prefix: t        #表名前缀
      table-underline: true   #表名是否使用下划线间隔，默认：是
  #config-location: mybatis-config.xml  #添加mybatis配置文件路径
  configuration:
    map-underscore-to-camel-case: true  #驼峰转下划线
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  type-enums-package: com.minlia.**.enums #配置枚举 支持通配符 * 或者 ; 分割
  type-aliases-package: com.minlia.**.entity #配置实体类包地址
#
swagger:
  enable: true
  host: http://localhost:${server.port}
  title: ${spring.application.name}
  version: 1.0
  path: /api/.*
  description: Hsjs Swagger
  termsOfServiceUrl: https://www.google.com/tos
  redirect: true
  contact:
    name: garen
    url: https://www.google.com
    email: cloud@google.com
#
#logging:
#  config: classpath:logback-spring.xml
#  file:
#    path: ./log
#  logback:
#    rollingpolicy:
#      max-history: 7
#      max-file-size: 10MB
#      total-size-cap: 20GB
#  charset:
#    file: UTF-8
#    console: UTF-8