server:
  port: 20000
  servlet:
    encoding:
      charset: UTF-8

system:
  appId: minlia-minlia
  token: 1==

# SPRING PROFILES
spring:
  profile: dev
  application:
    name: Game User
  http:
    encoding.enable: true
      encoding.force: true
  session:
    store-type: none

  datasource:
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/minlia?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
    name:
    username: root
    password: root
    #        使用druid数据源
    #        type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    continue-on-error: true
    initialize: true

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 300
      max-wait: 10000
      max-idle: 100
      min-idle: 50
    timeout: 0

system.security.jwt:
  tokenExpirationTime: 10080 # Number of minutes
  refreshTokenExpTime: 10080 # Minutes
  tokenIssuer: http://minlia.com
  tokenSigningKey: 1

swagger:
  title: ${spring.application.name}接口
  description: ${spring.application.name}接口
  version: 1.0
  contact: cloud@minlia.com
  path: /api/.*
  redirect: true

mybatis:
  #    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true