server:
    port: 10087

system:
    appId: module-bank-card
    token: bWlubGlhCg==

# SPRING PROFILES
spring:
    profile: dev
    application:
        name: Module Bank Card

    datasource:
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_dev?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
        name:
        username: root
        password:

    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            max-active: 300
            max-wait: 10000
            max-idle: 50
            min-idle: 10
        timeout: 180

system.security.jwt:
    tokenExpirationTime: 10080 # Number of minutes
    refreshTokenExpTime: 10080 # Minutes
    tokenIssuer: http://minlia.com
    tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus

swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 1.0
    contact: cloud@minlia.com
    path: /api/.*
    redirect: true

mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath*:mybatis/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

# 分页配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql