//package rules;
//
//import com.minlia.module.riskcontrol.enums.RiskLevelEnum
//import com.minlia.module.riskcontrol.service.RiskDimensionService
//import com.minlia.module.riskcontrol.service.RiskRecordService
//import com.minlia.module.rebecca.risk.event.RiskLoginEvent
//import com.minlia.module.riskcontrol.constant.RiskCode
//import com.minlia.module.rebecca.risk.event.RiskLoginEvent
//
//global RiskRecordService riskRecordService
//global DimensionService dimensionService
//
//rule "97_account_login_ip"
//    salience 97
//    lock-on-active true
//    when
//        event:RiskLoginEvent()
//    then
//        if (event.getScene().equals("NUM_DIFF_IP_LOGIN_15MINS")) {
//            long count  = dimensionService.distinctCountWithRedisAndConfig(event, new String[]{RiskLoginEvent.SCENE_VALUE}, RiskLoginEvent.IP);
//            if(!event.getLevel().equals(RiskLevelEnum.NORMAL)) {
//                riskRecordService.createEvent(event, RiskCode.Message.NUM_DIFF_IP_LOGIN_MINS, 15, count);
//            }
//        }
//end