package rules;

import com.minlia.module.riskcontrol.enums.RiskLevelEnum
import com.minlia.module.riskcontrol.service.DimensionService
import com.minlia.module.riskcontrol.service.RiskRecordService
import com.minlia.cloud.utils.ApiAssert
import com.minlia.modules.security.risk.event.RiskLoginEvent
import com.minlia.modules.rebecca.constant.UserCode

global RiskRecordService riskRecordService
global DimensionService dimensionService

rule "97_account_login_ip"
    salience 97
    lock-on-active true
    when
        event:RiskLoginEvent()
    then
        long count  = dimensionService.distinctCountWithRedisAndConfig(event, new String[]{RiskLoginEvent.USERNAME}, RiskLoginEvent.IP);
        String details = "同一个帐户15分钟内使用不同的IP登录系统,count=" + count;
        if(event.getLevel().equals(RiskLevelEnum.WARNING)) {
            riskRecordService.createEvent(event, details);
        } else if (event.getLevel().equals(RiskLevelEnum.DANGER)) {
            riskRecordService.createEvent(event, details);
        }
end