package rules;

import com.minlia.module.riskcontrol.event.Event
import com.minlia.module.riskcontrol.event.LoginEvent

//global DimensionService dimensionService

rule "0_all_addevent"
    salience 0
    lock-on-active true
    when
        loginEvent:LoginEvent()
    then
        System.out.println("dddddddddddddddd");
        System.out.println(loginEvent.getId());
        System.out.println(loginEvent.getMobile());
        System.out.println(loginEvent.getOperateIp());
end