server:
  port: 7001

system:
  appId: bibleapp
  token: bWlubGlhCg==

# SPRING PROFILES
spring:
  profile: dev
  application:
    name: 应用
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

  redis:
    database: 0
    host: 127.0.0.1
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 0

system.security.jwt:
  #  tokenExpirationTime: 15 # Number of minutes
  tokenExpirationTime: 604800 # Number of minutes
  refreshTokenExpTime: 604800 # Minutes
  tokenIssuer: http://minlia.com
  tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus

swagger:
  title: ${spring.application.name}接口
  description: ${spring.application.name}接口
  version: 1.0
  contact: cloud@minlia.com
  path: /api/.*
  redirect: true