package rules;

import com.minlia.module.riskcontrol.event.Event
import com.minlia.module.riskcontrol.enums.RiskLevelEnum
import com.minlia.module.riskcontrol.service.RiskRecordService

global RiskRecordService riskEventListService

rule "0_all_addevent"
    salience 0
    lock-on-active true
    when
        event:Event()
    then
        if(event.getLevel().equals(RiskLevelEnum.NORMAL)) {
            riskEventListService.createEvent(event);
        }
end