package rules;

import com.minlia.module.riskcontrol.event.Event
import com.minlia.module.riskcontrol.enums.RiskLevelEnum
import com.minlia.module.riskcontrol.service.RiskRecordService
import org.apache.commons.lang3.StringUtils

global RiskRecordService riskRecordService

rule "0_all_addevent"
    salience 0
    lock-on-active true
    when
        event:Event()
    then
        if(null != event.getLevel() && event.getLevel().equals(RiskLevelEnum.NORMAL)) {
            riskRecordService.createEvent(event);
        }
//        update(event);
end