package rules;

import com.minlia.module.riskcontrol.event.Event
import com.minlia.module.riskcontrol.event.LoginEvent

//global DimensionService dimensionService

rule "2_all_addevent"
    salience 2
    lock-on-active true
    when
        loginEvent:LoginEvent()
    then
        loginEvent.setOperateIp("a阿斯顿发撒地方的说");
        update(loginEvent);
        System.out.println("dddddddddddddddd");
        System.out.println(loginEvent.getEventId());
        System.out.println(loginEvent.getMobile());
        System.out.println(loginEvent.getOperateIp());
end