package rules;

import com.minlia.module.riskcontrol.event.LoginEvent
import com.minlia.module.riskcontrol.entity.BlackList
import com.minlia.module.riskcontrol.enums.RiskLevelEnum
import com.minlia.module.riskcontrol.enums.TimePeriodEnum
import com.minlia.module.riskcontrol.service.DimensionService
import com.minlia.module.riskcontrol.service.BlackListService
import com.minlia.module.riskcontrol.service.RiskRecordService

global BlackListService blackListService
global DimensionService dimensionService
global RiskRecordService riskRecordService

rule "98_login_ip"
    salience 98
    lock-on-active true
    when
        event:LoginEvent()
    then
        long count  = dimensionService.distinctCountWithRedisAndConfig(event, new String[]{LoginEvent.IP}, LoginEvent.USERNAME);
        String details = "近15分钟内同ip出现多个mobile,count=" + count;
        if(event.getLevel().equals(RiskLevelEnum.WARNING)) {
            riskRecordService.createEvent(event, details);
        } else if (event.getLevel().equals(RiskLevelEnum.DANGER)) {
            riskRecordService.createEvent(event, details);
            blackListService.pub(BlackList.builder().type(BlackList.EnumType.BLACK).dimension(BlackList.EnumDimension.IP).value(event.getIp()).time(event.getOperateTime()).detail(details).build());
        }
end