package rules;

import com.minlia.module.riskcontrol.event.Event
import com.minlia.module.riskcontrol.entity.RiskBlackList
import com.minlia.module.riskcontrol.service.RiskBlackListService
import com.minlia.cloud.utils.ApiAssert
import com.minlia.module.riskcontrol.entity.RiskBlackList

global RiskBlackListService riskBlackListService

/**
 * 黑名单-IP
 */
rule "999_all_black_ip"
    salience 999
    lock-on-active true
    when
        event:Event()
    then
        if (null != event.getIp()) {
            boolean exists = riskBlackListService.contain(RiskBlackList.EnumDimension.IP, RiskBlackList.EnumType.BLACK, event.getIp());
            if(exists) {
                ApiAssert.state(!exists, "10000", "黑名单");
            }
        }
end