package rules;

import com.minlia.module.riskcontrol.event.Event
import com.minlia.module.riskcontrol.entity.RiskBlackList
import com.minlia.module.riskcontrol.service.RiskBlackListService
import com.minlia.cloud.utils.ApiAssert
import com.minlia.module.riskcontrol.entity.RiskBlackList
import org.apache.commons.lang3.StringUtils
import com.minlia.module.riskcontrol.constant.RiskCode

global RiskBlackListService riskBlackListService

/**
 * 黑名单-IP
 */
rule "999_all_black_ip"
    salience 999
    lock-on-active true
    when
        event:Event()
    then
        if (StringUtils.isNotBlank(event.getIp())) {
            boolean exists = riskBlackListService.contain(RiskBlackList.EnumDimension.IP, RiskBlackList.EnumType.BLACK, event.getIp());
            ApiAssert.state(!exists, RiskCode.Message.BLACK_IP);
        }
end