//package rules;
//
//import com.minlia.module.riskcontrol.event.RiskLoginEvent
//import com.minlia.module.riskcontrol.entity.RiskBlackList
//import com.minlia.module.riskcontrol.enums.RiskLevelEnum
//import com.minlia.module.riskcontrol.enums.TimePeriodEnum
//import com.minlia.module.riskcontrol.service.DimensionService
//import com.minlia.module.riskcontrol.service.RiskBlackListService
//import com.minlia.module.riskcontrol.service.RiskRecordService
//import com.minlia.cloud.utils.ApiAssert
//import com.minlia.module.riskcontrol.event.RiskLoginEvent
//import com.minlia.module.riskcontrol.constant.RiskCode
//
//global RiskRecordService riskRecordService
//global DimensionService dimensionService
//
//rule "97_account_login_ip"
//    salience 97
//    lock-on-active true
//    when
//        event:RiskLoginEvent()
//    then
//        long count  = dimensionService.distinctCountWithRedisAndConfig(event, new String[]{RiskLoginEvent.USERNAME}, RiskLoginEvent.IP);
//        String details = "同一个帐户15分钟内使用不同的IP登录系统,count=" + count;
//        if(event.getLevel().equals(RiskLevelEnum.WARNING)) {
//            riskRecordService.createEvent(event, details);
//        } else if (event.getLevel().equals(RiskLevelEnum.DANGER)) {
//            riskRecordService.createEvent(event, details);
//            ApiAssert.state(false, RiskCode.Message.SAME_ACCOUNT_DIFFERENT_LOGIN_IP);
//        }
//end