#security:
#    sessions: never
#spring:
#    jackson:
#        joda-date-time-format: yyyy-MM-dd HH:mm:ss
#        date-format: yyyy-MM-dd HH:mm:ss
#        serialization:
#            write_dates_as_timestamps: true
#    mvc:
#        favicon:
#            enabled: false
