server:
  port: 30003

system:
  appId: walletapp
  token: bWlubGlhCg==

spring:
  profile: dev
  application:
    name: walletapp

  datasource:
    testOnBorrow: true
    validationQuery: "SELECT 1"
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/minlia_modules_sesame_dev_v1?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: Root.2018

#    jpa:
##        database-platform: org.hibernate.dialect.H2Dialect
##        database: H2
#        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#        database: MYSQL
#        show_sql: false
#        properties:
#          jadira.usertype.autoRegisterUserTypes: true
#        hibernate:
##            naming:
##                strategy:
##            ddl-auto: update
#            ddl-auto: create-drop

security.jwt:
  tokenExpirationTime: 10080 # Number of minutes
  refreshTokenExpTime: 10080 # Minutes
  tokenIssuer: http://minlia.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

swagger:
  title: ${spring.application.name}接口
  description: ${spring.application.name}接口
  version: 2.0
  contact: cloud@minlia.com
  path: /api/.*

