
package com.minlia.module.nestedset.config.mem.identity;

/*-
 * #%L
 * minlia
 * %%
 * Copyright (C) 2005 - 2020 Minlia, Inc
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.io.Serializable;

/**
 * Identity generator used for inserting new Nodes into an InMemory Repository.
 * If you want to have an interoperability between InMemory implementation and DB-based implementation, make sure that
 * IDs generated by implementation of ths interface are compatible with your database configuration.
 *
 * @param <ID> - Nested Node ID Class
 */
public interface InMemoryNestedNodeIdentityGenerator<ID extends Serializable> {

    /**
     * Generates a unique identity for InMemory repository Node insertion
     *
     * @return ID - newly generated unique identity
     */
    ID generateIdentity();
}
