#
swagger:
  enable: true
  host: http://localhost:${server.port}
  title: ${spring.application.name}
  version: 1.0
  path: /api/.*
  description: NFT Swagger
  termsOfServiceUrl: https://www.google.com/tos
  redirect: true
  contact:
    name: garen
    url: https://www.google.com
    email: cloud@google.com